package memory

import (
	"context"
)

// VectorRecord represents a single record in the vector database.
type VectorRecord struct {
	ID      string                 `json:"id"`
	Vector  []float32              `json:"vector"`
	Payload map[string]interface{} `json:"payload"`
}

// SearchResult represents a result from a vector search.
type SearchResult struct {
	ID      string                 `json:"id"`
	Score   float32                `json:"score"`
	Payload map[string]interface{} `json:"payload"`
}

// VectorDB defines the interface for interacting with vector databases.
type VectorDB interface {
	// Store inserts or updates a vector record in the specified collection.
	Store(ctx context.Context, collection string, record VectorRecord) error

	// Search finds the nearest neighbors and applies filters in the specified collection.
	Search(ctx context.Context, collection string, vector []float32, limit, offset int, filters map[string]interface{}) ([]SearchResult, error)

	// EnsureCollection ensures that the specified collection exists with the correct dimension.
	EnsureCollection(ctx context.Context, name string, dimension int) error

	// Close closes the connection to the vector database.
	Close() error
}

// Embedder defines the interface for generating text embeddings.
type Embedder interface {
	// Embed generates an embedding for the given text.
	Embed(ctx context.Context, text string) ([]float32, error)

	// Dimension returns the size of the embeddings generated by this embedder.
	Dimension() int
}
